apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: drop
resources:
  - ../../base
images:
  - name: drop
    newName: drop
    newTag: dev
patches:
  - path: deployment-patch.yaml
